encoding: utf-8
exclude: ["Gemfile", "Gemfile.lock", "CNAME", "LICENSE", "README.md"]
sass:
  sass_dir: _sass
  style: compressed

title: "Speed Dial"
url: "https://link.39.gy"
icon: "https://res.cloudinary.com/dagsofv2s/image/upload/q_auto:good/logo.png"

author:
  name: "ress"
